name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Change this to use runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptium'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the Java project with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run unit tests
      - name: Run tests with Maven
        run: mvn test

      # Optional: Deploy Java app (if needed)
      - name: Deploy Java app
        run: |
          echo "Deploying Java app..."
